# Generated by Django 5.0.6 on 2024-07-28 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_remove_post_like_count_post_like_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='like_count',
            new_name='liked_users',
        ),
    ]
